### ISSUE TITLE
Summary endpoint not working

### ISSUE THREAD

**Issue by Angeluz-07** [ioet/time-tracker-backend#142]
`/summary` endpoint it seems to be working locally, but the same version deployed is not.

**Comment by ralden** [comment]
This is the #1 ticket in the world. There has never been a software project where this ticket has not been required. In Jira, this ticket is automatically created. If it is accidently closed, it is automatically reopened. The github issue tracker does not have this feature because in most open source projects this behavior is a feature, not an error.

**Comment by Angeluz-07** [comment]
I was reproducing this error with two users. It seems that week and day time-entries were not taken into account into the computed worked time. 

Unfortunately, this issue stop happening after around ~14:20 pm without any change. So It couldn't be reproduced. I will left this issue opened.

**Comment by Angeluz-07** [comment]
There was an important refactor in #173 that should allow to debug issues like this. Closing it.
